x-webui-common: &webui-common
  build: ./services/webui
  ports:
    - 8501:8501

x-artifact-mounts: &artifact-mounts
  - ./src/features.py:/app/features.py:ro
  - ./artifacts/extractor.pkl:/app/extractor.pkl:ro
  - ./artifacts/model.onnx:/app/model.onnx:ro

services:
  # Triton Inference Server
  triton:
    profiles:
      - triton
      - parity
    container_name: clml-tritonserver
    build: ./services/triton
    ports:
      - 8000:8000 # HTTP API
      - 8001:8001 # gRPC API
      - 8002:8002 # Metrics Monitoring
    restart: always
    volumes:
      - ./model_repository:/models
      - ./src/features.py:/models/feature_extractor/1/features.py:ro
      - ./artifacts/extractor.pkl:/models/feature_extractor/1/extractor.pkl:ro
      - ./artifacts/model.onnx:/models/titanic_classifier/1/model.onnx:ro
    command: [ "tritonserver", "--model-repository=/models" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/v2/health/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # App api
  api-triton:
    profiles:
      - triton
    build: ./services/api_triton
    container_name: clml-app-triton
    ports:
      - 8080:8080
    environment:
      - TRITON_URL=triton:8001
    depends_on:
      triton:
        condition: service_healthy

  api-fastapi:
    profiles:
      - fastapi
    build: ./services/api_fastapi
    container_name: clml-app-fastapi
    ports:
      - 8080:8080
    volumes: *artifact-mounts

  # Parity profile
  parity-fastapi:
    profiles:
      - parity
    build: ./services/api_fastapi
    container_name: clml-parity-fastapi
    ports:
      - 8081:8080
    volumes: *artifact-mounts

  parity-triton:
    profiles:
      - parity
    build: ./services/api_triton
    container_name: clml-parity-triton
    ports:
      - 8082:8080
    environment:
      - TRITON_URL=triton:8001
    depends_on:
      triton:
        condition: service_healthy

  # Web UI
  webui-triton:
    <<: *webui-common
    profiles:
      - triton
    container_name: clml-webui-triton
    environment:
      - API_URL=http://api-triton:8080
      # - UI_SCALE=1.5
    depends_on:
      - api-triton

  webui-fastapi:
    <<: *webui-common
    profiles:
      - fastapi
    container_name: clml-webui-fastapi
    environment:
      - API_URL=http://api-fastapi:8080
      # - UI_SCALE=1.5
    depends_on:
      - api-fastapi
