FROM python:3.12

COPY --from=ghcr.io/astral-sh/uv:0.12 /uv /usr/local/bin/uv

WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-dev

COPY app.py .

CMD [ ".venv/bin/uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080" ]
