name: "titanic_classifier"
backend: "onnxruntime"
max_batch_size: 32

input [
  { name: "Pclass",       data_type: TYPE_FP32,   dims: [ 1 ] },
  { name: "Age",          data_type: TYPE_FP32,   dims: [ 1 ] },
  { name: "SibSp",        data_type: TYPE_FP32,   dims: [ 1 ] },
  { name: "Parch",        data_type: TYPE_FP32,   dims: [ 1 ] },
  { name: "Fare",         data_type: TYPE_FP32,   dims: [ 1 ] },
  { name: "HasCabin",     data_type: TYPE_FP32,   dims: [ 1 ] },
  { name: "CabinCount",   data_type: TYPE_FP32,   dims: [ 1 ] },
  { name: "GroupSize",    data_type: TYPE_FP32,   dims: [ 1 ] },
  { name: "NameLen",      data_type: TYPE_FP32,   dims: [ 1 ] },
  { name: "Sex",          data_type: TYPE_STRING, dims: [ 1 ] },
  { name: "Embarked",     data_type: TYPE_STRING, dims: [ 1 ] },
  { name: "Deck",         data_type: TYPE_STRING, dims: [ 1 ] },
  { name: "TicketPrefix", data_type: TYPE_STRING, dims: [ 1 ] },
  { name: "Title",        data_type: TYPE_STRING, dims: [ 1 ] }
]

output [
  { name: "label",         data_type: TYPE_INT64, dims: [ 1 ], reshape: { shape: [ ] } },
  { name: "probabilities", data_type: TYPE_FP32,  dims: [ 2 ] }
]
